// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
)

const eventAnalytics = `-- name: EventAnalytics :one
WITH scope AS (
 SELECT now() AS through, now() - make_interval(secs => $2::int) AS since
), events AS (
 SELECT floor(extract(epoch FROM (b.created_at-s.since))*60/$2::int)::int AS bucket,
        b.envelope->>'status' AS status,
        b.envelope->>'instance' AS instance
 FROM journal_batches b, scope s
 WHERE b.run_id=$3 AND b.created_at>=s.since AND b.created_at<s.through
 AND ($1::text='' OR b.envelope->'command'->>'currency'=$1
 OR (coalesce(b.envelope->'command'->>'currency','')='' AND EXISTS (
 SELECT FROM postings p WHERE p.run_id=b.run_id AND p.sequence=b.sequence AND p.currency=$1)))
), counts AS (
 SELECT bucket, count(*) AS total,
 count(*) FILTER (WHERE status='accepted') AS accepted,
 count(*) FILTER (WHERE status='declined') AS declined,
 count(*) FILTER (WHERE status='rejected') AS rejected
 FROM events GROUP BY bucket
), buckets AS (
 SELECT n, s.since + (s.through-s.since)*n/60 AS at,
 coalesce(c.total,0) AS total,
 coalesce(c.accepted,0) AS accepted,
 coalesce(c.declined,0) AS declined,
 coalesce(c.rejected,0) AS rejected
 FROM scope s CROSS JOIN generate_series(0,59) n
 LEFT JOIN counts c ON c.bucket=n
)
SELECT jsonb_build_object('since',s.since,'through',s.through,'currency',$1::text,
 'bucket_seconds',$2::int/60,
 'buckets',(SELECT jsonb_agg(jsonb_build_object('at',at,'total',total,'accepted',accepted,'declined',declined,'rejected',rejected) ORDER BY n) FROM buckets),
 'instances',coalesce((SELECT jsonb_agg(row_to_json(i)) FROM (SELECT coalesce(instance,'unknown') AS instance,count(*) AS total FROM events GROUP BY instance ORDER BY instance) i),'[]'::jsonb))::jsonb
FROM scope s
`

type EventAnalyticsParams struct {
	Currency string `json:"currency"`
	Seconds  int32  `json:"seconds"`
	RunID    string `json:"run_id"`
}

// One snapshot, 60 equal buckets. Currency is the command currency; legacy
// records without it fall back to posting currencies. Unattributed decisions
// belong only to the all-currency view. Retries do not create new decisions.
func (q *Queries) EventAnalytics(ctx context.Context, arg EventAnalyticsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, eventAnalytics, arg.Currency, arg.Seconds, arg.RunID)
	var column_1 []byte
	err := row.Scan(&column_1)
	return column_1, err
}
