// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment.sql

package db

import (
	"context"
)

const assessedFeeDays = `-- name: AssessedFeeDays :many
SELECT value_day FROM fee_assessments WHERE run_id = $1 AND account_id = $2
`

type AssessedFeeDaysParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) AssessedFeeDays(ctx context.Context, arg AssessedFeeDaysParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, assessedFeeDays, arg.RunID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var value_day int32
		if err := rows.Scan(&value_day); err != nil {
			return nil, err
		}
		items = append(items, value_day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finalizeRun = `-- name: FinalizeRun :exec
UPDATE runs SET finalized = true WHERE id = $1
`

func (q *Queries) FinalizeRun(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, finalizeRun, id)
	return err
}

const findReversibleDebit = `-- name: FindReversibleDebit :one
SELECT p.run_id, p.sequence, p.leg, p.account_id, p.currency, p.units, p.value_day, p.kind FROM postings p JOIN journal_batches b USING (run_id, sequence)
WHERE p.run_id = $1 AND p.account_id = $2 AND b.command_id = $3
AND p.kind = 'debit' AND p.units > 0
`

type FindReversibleDebitParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	CommandID string `json:"command_id"`
}

func (q *Queries) FindReversibleDebit(ctx context.Context, arg FindReversibleDebitParams) (Posting, error) {
	row := q.db.QueryRow(ctx, findReversibleDebit, arg.RunID, arg.AccountID, arg.CommandID)
	var i Posting
	err := row.Scan(
		&i.RunID,
		&i.Sequence,
		&i.Leg,
		&i.AccountID,
		&i.Currency,
		&i.Units,
		&i.ValueDay,
		&i.Kind,
	)
	return i, err
}

const historicalBalance = `-- name: HistoricalBalance :one
SELECT COALESCE(sum(-p.units::numeric), 0)::bigint AS balance
FROM postings p
WHERE p.run_id = $1 AND p.account_id = $2
AND p.value_day <= $3
AND ($4::bigint = 0 OR p.sequence <= $4)
`

type HistoricalBalanceParams struct {
	RunID        string `json:"run_id"`
	AccountID    string `json:"account_id"`
	ValueDay     int32  `json:"value_day"`
	KnownThrough int64  `json:"known_through"`
}

func (q *Queries) HistoricalBalance(ctx context.Context, arg HistoricalBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, historicalBalance,
		arg.RunID,
		arg.AccountID,
		arg.ValueDay,
		arg.KnownThrough,
	)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const latestBookedDay = `-- name: LatestBookedDay :one
SELECT COALESCE(max(booked_day), 0)::integer AS day
FROM journal_batches WHERE run_id = $1
`

func (q *Queries) LatestBookedDay(ctx context.Context, runID string) (int32, error) {
	row := q.db.QueryRow(ctx, latestBookedDay, runID)
	var day int32
	err := row.Scan(&day)
	return day, err
}

const lockFinalization = `-- name: LockFinalization :one
SELECT id, profile, created_at, day, policy, finalized FROM runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockFinalization(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRow(ctx, lockFinalization, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.CreatedAt,
		&i.Day,
		&i.Policy,
		&i.Finalized,
	)
	return i, err
}

const recordFee = `-- name: RecordFee :exec
INSERT INTO fee_assessments (run_id, account_id, value_day) VALUES ($1, $2, $3)
`

type RecordFeeParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	ValueDay  int32  `json:"value_day"`
}

func (q *Queries) RecordFee(ctx context.Context, arg RecordFeeParams) error {
	_, err := q.db.Exec(ctx, recordFee, arg.RunID, arg.AccountID, arg.ValueDay)
	return err
}

const recordPeriod = `-- name: RecordPeriod :exec
INSERT INTO periods (run_id, start_day, through_day, command_id) VALUES ($1, $2, $3, $4)
`

type RecordPeriodParams struct {
	RunID      string `json:"run_id"`
	StartDay   int32  `json:"start_day"`
	ThroughDay int32  `json:"through_day"`
	CommandID  string `json:"command_id"`
}

func (q *Queries) RecordPeriod(ctx context.Context, arg RecordPeriodParams) error {
	_, err := q.db.Exec(ctx, recordPeriod,
		arg.RunID,
		arg.StartDay,
		arg.ThroughDay,
		arg.CommandID,
	)
	return err
}

const recordReversal = `-- name: RecordReversal :execrows
INSERT INTO reversals (run_id, target_event, command_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type RecordReversalParams struct {
	RunID       string `json:"run_id"`
	TargetEvent string `json:"target_event"`
	CommandID   string `json:"command_id"`
}

func (q *Queries) RecordReversal(ctx context.Context, arg RecordReversalParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordReversal, arg.RunID, arg.TargetEvent, arg.CommandID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
