// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (run_id, id, name, currency, class, customer)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING
`

type CreateAccountParams struct {
	RunID    string `json:"run_id"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Class    string `json:"class"`
	Customer bool   `json:"customer"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.RunID,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.Class,
		arg.Customer,
	)
	return err
}

const createClock = `-- name: CreateClock :exec
INSERT INTO journal_clock (run_id) VALUES ($1)
`

func (q *Queries) CreateClock(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, createClock, runID)
	return err
}

const createControls = `-- name: CreateControls :exec
INSERT INTO controls (run_id, eps) VALUES ($1, 0)
`

func (q *Queries) CreateControls(ctx context.Context, runID string) error {
	_, err := q.db.Exec(ctx, createControls, runID)
	return err
}

const createDemoClock = `-- name: CreateDemoClock :exec
INSERT INTO journal_clock (run_id) VALUES ('demo') ON CONFLICT DO NOTHING
`

func (q *Queries) CreateDemoClock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createDemoClock)
	return err
}

const createDemoControls = `-- name: CreateDemoControls :exec
INSERT INTO controls (run_id) VALUES ('demo') ON CONFLICT DO NOTHING
`

func (q *Queries) CreateDemoControls(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createDemoControls)
	return err
}

const createDemoRun = `-- name: CreateDemoRun :exec
INSERT INTO runs (id, profile) VALUES ('demo', 'live') ON CONFLICT DO NOTHING
`

func (q *Queries) CreateDemoRun(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createDemoRun)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, profile, policy) VALUES ($1, $2,
 jsonb_build_object('version', CASE WHEN $2 = 'fixture' THEN 'assessment-v1' ELSE 'simulation-v1' END,
 'fee_aed', 2500, 'rate_numerator', 1, 'rate_denominator', 2500))
`

type CreateRunParams struct {
	ID      string `json:"id"`
	Profile string `json:"profile"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.Exec(ctx, createRun, arg.ID, arg.Profile)
	return err
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock(937413)
`

func (q *Queries) LockBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockBootstrap)
	return err
}
