// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package db

import (
	"context"
)

const advanceRunDay = `-- name: AdvanceRunDay :exec
UPDATE runs SET day=$2 WHERE id=$1
`

type AdvanceRunDayParams struct {
	ID  string `json:"id"`
	Day int32  `json:"day"`
}

func (q *Queries) AdvanceRunDay(ctx context.Context, arg AdvanceRunDayParams) error {
	_, err := q.db.Exec(ctx, advanceRunDay, arg.ID, arg.Day)
	return err
}

const findDayTransition = `-- name: FindDayTransition :one
SELECT run_id, from_day, to_day, recorded_at, instance FROM day_transitions WHERE run_id=$1 AND from_day=$2
`

type FindDayTransitionParams struct {
	RunID   string `json:"run_id"`
	FromDay int32  `json:"from_day"`
}

func (q *Queries) FindDayTransition(ctx context.Context, arg FindDayTransitionParams) (DayTransition, error) {
	row := q.db.QueryRow(ctx, findDayTransition, arg.RunID, arg.FromDay)
	var i DayTransition
	err := row.Scan(
		&i.RunID,
		&i.FromDay,
		&i.ToDay,
		&i.RecordedAt,
		&i.Instance,
	)
	return i, err
}

const lockAccountCloseJob = `-- name: LockAccountCloseJob :one
SELECT run_id, account_id, day, state, reason FROM account_close_jobs WHERE run_id=$1 AND account_id=$2 AND day=$3 FOR UPDATE
`

type LockAccountCloseJobParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	Day       int32  `json:"day"`
}

func (q *Queries) LockAccountCloseJob(ctx context.Context, arg LockAccountCloseJobParams) (AccountCloseJob, error) {
	row := q.db.QueryRow(ctx, lockAccountCloseJob, arg.RunID, arg.AccountID, arg.Day)
	var i AccountCloseJob
	err := row.Scan(
		&i.RunID,
		&i.AccountID,
		&i.Day,
		&i.State,
		&i.Reason,
	)
	return i, err
}

const pendingAccountCloses = `-- name: PendingAccountCloses :one
SELECT count(*) FROM account_close_jobs
WHERE run_id=$1 AND account_id=$2 AND state<>'done'
`

type PendingAccountClosesParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) PendingAccountCloses(ctx context.Context, arg PendingAccountClosesParams) (int64, error) {
	row := q.db.QueryRow(ctx, pendingAccountCloses, arg.RunID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pendingRunCloses = `-- name: PendingRunCloses :one
SELECT count(*) FROM account_close_jobs WHERE run_id=$1 AND state<>'done'
`

func (q *Queries) PendingRunCloses(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, pendingRunCloses, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const priorPeriodCloses = `-- name: PriorPeriodCloses :many
SELECT j.day,b.envelope AS response FROM account_close_jobs j
JOIN command_results c ON c.run_id=j.run_id AND c.id='system:close:'||j.day::text||':'||j.account_id
JOIN journal_batches b ON b.run_id=c.run_id AND b.sequence=(c.response->>'sequence')::bigint
 AND b.command_id=c.id AND b.kind='account_close'
WHERE j.run_id=$1 AND j.account_id=$2 AND j.day>=$3::integer
 AND j.day<$4::integer AND j.state='done'
ORDER BY j.day
`

type PriorPeriodClosesParams struct {
	RunID      string `json:"run_id"`
	AccountID  string `json:"account_id"`
	StartDay   int32  `json:"start_day"`
	ThroughDay int32  `json:"through_day"`
}

type PriorPeriodClosesRow struct {
	Day      int32  `json:"day"`
	Response []byte `json:"response"`
}

func (q *Queries) PriorPeriodCloses(ctx context.Context, arg PriorPeriodClosesParams) ([]PriorPeriodClosesRow, error) {
	rows, err := q.db.Query(ctx, priorPeriodCloses,
		arg.RunID,
		arg.AccountID,
		arg.StartDay,
		arg.ThroughDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriorPeriodClosesRow{}
	for rows.Next() {
		var i PriorPeriodClosesRow
		if err := rows.Scan(&i.Day, &i.Response); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAccountPeriod = `-- name: RecordAccountPeriod :exec
INSERT INTO account_periods(run_id,account_id,start_day,through_day,sequence,amount)
VALUES($1,$2,$3,$4,$5,$6)
`

type RecordAccountPeriodParams struct {
	RunID      string `json:"run_id"`
	AccountID  string `json:"account_id"`
	StartDay   int32  `json:"start_day"`
	ThroughDay int32  `json:"through_day"`
	Sequence   int64  `json:"sequence"`
	Amount     int64  `json:"amount"`
}

func (q *Queries) RecordAccountPeriod(ctx context.Context, arg RecordAccountPeriodParams) error {
	_, err := q.db.Exec(ctx, recordAccountPeriod,
		arg.RunID,
		arg.AccountID,
		arg.StartDay,
		arg.ThroughDay,
		arg.Sequence,
		arg.Amount,
	)
	return err
}

const recordDayTransition = `-- name: RecordDayTransition :exec
INSERT INTO day_transitions(run_id,from_day,to_day,instance) VALUES($1,$2,$3,$4)
`

type RecordDayTransitionParams struct {
	RunID    string `json:"run_id"`
	FromDay  int32  `json:"from_day"`
	ToDay    int32  `json:"to_day"`
	Instance string `json:"instance"`
}

func (q *Queries) RecordDayTransition(ctx context.Context, arg RecordDayTransitionParams) error {
	_, err := q.db.Exec(ctx, recordDayTransition,
		arg.RunID,
		arg.FromDay,
		arg.ToDay,
		arg.Instance,
	)
	return err
}

const scheduleAccountCloses = `-- name: ScheduleAccountCloses :exec
INSERT INTO account_close_jobs(run_id,account_id,day)
SELECT a.run_id,a.id,$1::integer FROM accounts a WHERE a.run_id=$2 AND a.customer
`

type ScheduleAccountClosesParams struct {
	Day   int32  `json:"day"`
	RunID string `json:"run_id"`
}

func (q *Queries) ScheduleAccountCloses(ctx context.Context, arg ScheduleAccountClosesParams) error {
	_, err := q.db.Exec(ctx, scheduleAccountCloses, arg.Day, arg.RunID)
	return err
}

const setAccountCloseJob = `-- name: SetAccountCloseJob :exec
UPDATE account_close_jobs SET state=$4,reason=$5 WHERE run_id=$1 AND account_id=$2 AND day=$3
`

type SetAccountCloseJobParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	Day       int32  `json:"day"`
	State     string `json:"state"`
	Reason    string `json:"reason"`
}

func (q *Queries) SetAccountCloseJob(ctx context.Context, arg SetAccountCloseJobParams) error {
	_, err := q.db.Exec(ctx, setAccountCloseJob,
		arg.RunID,
		arg.AccountID,
		arg.Day,
		arg.State,
		arg.Reason,
	)
	return err
}
