// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package db

import (
	"context"
)

const advanceRunDay = `-- name: AdvanceRunDay :exec
UPDATE runs SET day=$2 WHERE id=$1
`

type AdvanceRunDayParams struct {
	ID  string `json:"id"`
	Day int32  `json:"day"`
}

func (q *Queries) AdvanceRunDay(ctx context.Context, arg AdvanceRunDayParams) error {
	_, err := q.db.Exec(ctx, advanceRunDay, arg.ID, arg.Day)
	return err
}

const findDayTransition = `-- name: FindDayTransition :one
SELECT run_id, from_day, to_day, recorded_at, instance FROM day_transitions WHERE run_id=$1 AND from_day=$2
`

type FindDayTransitionParams struct {
	RunID   string `json:"run_id"`
	FromDay int32  `json:"from_day"`
}

func (q *Queries) FindDayTransition(ctx context.Context, arg FindDayTransitionParams) (DayTransition, error) {
	row := q.db.QueryRow(ctx, findDayTransition, arg.RunID, arg.FromDay)
	var i DayTransition
	err := row.Scan(
		&i.RunID,
		&i.FromDay,
		&i.ToDay,
		&i.RecordedAt,
		&i.Instance,
	)
	return i, err
}

const pendingAccountCloses = `-- name: PendingAccountCloses :one
SELECT count(*) FROM account_close_jobs
WHERE run_id=$1 AND account_id=$2 AND state<>'done'
`

type PendingAccountClosesParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) PendingAccountCloses(ctx context.Context, arg PendingAccountClosesParams) (int64, error) {
	row := q.db.QueryRow(ctx, pendingAccountCloses, arg.RunID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pendingRunCloses = `-- name: PendingRunCloses :one
SELECT count(*) FROM account_close_jobs WHERE run_id=$1 AND state<>'done'
`

func (q *Queries) PendingRunCloses(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, pendingRunCloses, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordDayTransition = `-- name: RecordDayTransition :exec
INSERT INTO day_transitions(run_id,from_day,to_day,instance) VALUES($1,$2,$3,$4)
`

type RecordDayTransitionParams struct {
	RunID    string `json:"run_id"`
	FromDay  int32  `json:"from_day"`
	ToDay    int32  `json:"to_day"`
	Instance string `json:"instance"`
}

func (q *Queries) RecordDayTransition(ctx context.Context, arg RecordDayTransitionParams) error {
	_, err := q.db.Exec(ctx, recordDayTransition,
		arg.RunID,
		arg.FromDay,
		arg.ToDay,
		arg.Instance,
	)
	return err
}

const scheduleAccountCloses = `-- name: ScheduleAccountCloses :exec
INSERT INTO account_close_jobs(run_id,account_id,day)
SELECT a.run_id,a.id,$1::integer FROM accounts a WHERE a.run_id=$2 AND a.customer
`

type ScheduleAccountClosesParams struct {
	Day   int32  `json:"day"`
	RunID string `json:"run_id"`
}

func (q *Queries) ScheduleAccountCloses(ctx context.Context, arg ScheduleAccountClosesParams) error {
	_, err := q.db.Exec(ctx, scheduleAccountCloses, arg.Day, arg.RunID)
	return err
}
