// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_guard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hostGuardStatus = `-- name: HostGuardStatus :one
SELECT observed_at, safe_until > now() AS safe, reason, evidence FROM host_guard WHERE id
`

type HostGuardStatusRow struct {
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Safe       bool               `json:"safe"`
	Reason     string             `json:"reason"`
	Evidence   []byte             `json:"evidence"`
}

func (q *Queries) HostGuardStatus(ctx context.Context) (HostGuardStatusRow, error) {
	row := q.db.QueryRow(ctx, hostGuardStatus)
	var i HostGuardStatusRow
	err := row.Scan(
		&i.ObservedAt,
		&i.Safe,
		&i.Reason,
		&i.Evidence,
	)
	return i, err
}

const publishHostGuard = `-- name: PublishHostGuard :exec
INSERT INTO host_guard (id, observed_at, safe_until, reason, evidence)
VALUES (true, now(), CASE WHEN $1::text = '' THEN now() + interval '8 seconds' ELSE now() END,
 $1, $2)
ON CONFLICT (id) DO UPDATE SET observed_at = excluded.observed_at,
 safe_until = excluded.safe_until, reason = excluded.reason, evidence = excluded.evidence
`

type PublishHostGuardParams struct {
	Reason   string `json:"reason"`
	Evidence []byte `json:"evidence"`
}

func (q *Queries) PublishHostGuard(ctx context.Context, arg PublishHostGuardParams) error {
	_, err := q.db.Exec(ctx, publishHostGuard, arg.Reason, arg.Evidence)
	return err
}
