// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"
)

const appendBatch = `-- name: AppendBatch :exec
INSERT INTO journal_batches (run_id, sequence, command_id, kind, booked_day, value_day, instance, envelope)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendBatchParams struct {
	RunID     string `json:"run_id"`
	Sequence  int64  `json:"sequence"`
	CommandID string `json:"command_id"`
	Kind      string `json:"kind"`
	BookedDay int32  `json:"booked_day"`
	ValueDay  int32  `json:"value_day"`
	Instance  string `json:"instance"`
	Envelope  []byte `json:"envelope"`
}

func (q *Queries) AppendBatch(ctx context.Context, arg AppendBatchParams) error {
	_, err := q.db.Exec(ctx, appendBatch,
		arg.RunID,
		arg.Sequence,
		arg.CommandID,
		arg.Kind,
		arg.BookedDay,
		arg.ValueDay,
		arg.Instance,
		arg.Envelope,
	)
	return err
}

const appendPosting = `-- name: AppendPosting :exec
INSERT INTO postings (run_id, sequence, leg, account_id, currency, units)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendPostingParams struct {
	RunID     string `json:"run_id"`
	Sequence  int64  `json:"sequence"`
	Leg       int32  `json:"leg"`
	AccountID string `json:"account_id"`
	Currency  string `json:"currency"`
	Units     int64  `json:"units"`
}

func (q *Queries) AppendPosting(ctx context.Context, arg AppendPostingParams) error {
	_, err := q.db.Exec(ctx, appendPosting,
		arg.RunID,
		arg.Sequence,
		arg.Leg,
		arg.AccountID,
		arg.Currency,
		arg.Units,
	)
	return err
}

const captureHold = `-- name: CaptureHold :exec
UPDATE holds SET state = 'captured', captured = $3, released = $4
WHERE run_id = $1 AND id = $2
`

type CaptureHoldParams struct {
	RunID    string `json:"run_id"`
	ID       string `json:"id"`
	Captured int64  `json:"captured"`
	Released int64  `json:"released"`
}

func (q *Queries) CaptureHold(ctx context.Context, arg CaptureHoldParams) error {
	_, err := q.db.Exec(ctx, captureHold,
		arg.RunID,
		arg.ID,
		arg.Captured,
		arg.Released,
	)
	return err
}

const claimCommand = `-- name: ClaimCommand :exec
INSERT INTO command_results (run_id, id, hash) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimCommandParams struct {
	RunID string `json:"run_id"`
	ID    string `json:"id"`
	Hash  string `json:"hash"`
}

func (q *Queries) ClaimCommand(ctx context.Context, arg ClaimCommandParams) error {
	_, err := q.db.Exec(ctx, claimCommand, arg.RunID, arg.ID, arg.Hash)
	return err
}

const completeCommand = `-- name: CompleteCommand :exec
UPDATE command_results SET response = $3 WHERE run_id = $1 AND id = $2
`

type CompleteCommandParams struct {
	RunID    string `json:"run_id"`
	ID       string `json:"id"`
	Response []byte `json:"response"`
}

func (q *Queries) CompleteCommand(ctx context.Context, arg CompleteCommandParams) error {
	_, err := q.db.Exec(ctx, completeCommand, arg.RunID, arg.ID, arg.Response)
	return err
}

const countBalanceDifferences = `-- name: CountBalanceDifferences :one
SELECT count(*) FROM accounts a LEFT JOIN (
  SELECT account_id, sum(units) units FROM postings WHERE postings.run_id = $1 GROUP BY account_id
) p ON p.account_id = a.id
WHERE a.run_id = $1 AND a.balance <> COALESCE(p.units, 0) *
  CASE WHEN a.class IN ('liability', 'income', 'equity') THEN -1 ELSE 1 END
`

func (q *Queries) CountBalanceDifferences(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBalanceDifferences, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHoldDifferences = `-- name: CountHoldDifferences :one
SELECT count(*) FROM accounts a LEFT JOIN (
  SELECT account_id, sum(amount) amount FROM holds
  WHERE holds.run_id = $1 AND state = 'active' GROUP BY account_id
) h ON h.account_id = a.id
WHERE a.run_id = $1 AND a.held <> COALESCE(h.amount, 0)
`

func (q *Queries) CountHoldDifferences(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHoldDifferences, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnbalancedBatches = `-- name: CountUnbalancedBatches :one
SELECT count(*) FROM (
  SELECT sequence, currency FROM postings WHERE run_id = $1
  GROUP BY sequence, currency HAVING sum(units) <> 0
) x
`

func (q *Queries) CountUnbalancedBatches(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnbalancedBatches, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHold = `-- name: CreateHold :execrows
INSERT INTO holds (run_id, id, account_id, amount, state)
VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING
`

type CreateHoldParams struct {
	RunID     string `json:"run_id"`
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Amount    int64  `json:"amount"`
	State     string `json:"state"`
}

func (q *Queries) CreateHold(ctx context.Context, arg CreateHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, createHold,
		arg.RunID,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.State,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const currentSequence = `-- name: CurrentSequence :one
SELECT position FROM journal_clock WHERE run_id = $1
`

func (q *Queries) CurrentSequence(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, currentSequence, runID)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const enqueueDelivery = `-- name: EnqueueDelivery :exec
INSERT INTO outbox (run_id, sequence) VALUES ($1, $2)
`

type EnqueueDeliveryParams struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) EnqueueDelivery(ctx context.Context, arg EnqueueDeliveryParams) error {
	_, err := q.db.Exec(ctx, enqueueDelivery, arg.RunID, arg.Sequence)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT run_id, id, name, currency, class, customer, balance, held, version FROM accounts WHERE run_id = $1 ORDER BY id
`

func (q *Queries) ListAccounts(ctx context.Context, runID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.RunID,
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Class,
			&i.Customer,
			&i.Balance,
			&i.Held,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournal = `-- name: ListJournal :many
SELECT b.run_id, b.sequence, b.command_id, b.kind, b.booked_day, b.value_day, b.instance, b.created_at, b.envelope FROM journal_batches b
WHERE b.run_id = $1
  AND ($2::text = '' OR EXISTS (
    SELECT 1 FROM postings p WHERE p.run_id = b.run_id AND p.sequence = b.sequence
    AND p.account_id = $2))
  AND ($3::bigint = 0 OR b.sequence <= $3)
ORDER BY b.sequence DESC LIMIT 60
`

type ListJournalParams struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	Cutoff    int64  `json:"cutoff"`
}

func (q *Queries) ListJournal(ctx context.Context, arg ListJournalParams) ([]JournalBatch, error) {
	rows, err := q.db.Query(ctx, listJournal, arg.RunID, arg.AccountID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalBatch{}
	for rows.Next() {
		var i JournalBatch
		if err := rows.Scan(
			&i.RunID,
			&i.Sequence,
			&i.CommandID,
			&i.Kind,
			&i.BookedDay,
			&i.ValueDay,
			&i.Instance,
			&i.CreatedAt,
			&i.Envelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :one
SELECT run_id, id, name, currency, class, customer, balance, held, version FROM accounts WHERE run_id = $1 AND id = $2 FOR UPDATE
`

type LockAccountParams struct {
	RunID string `json:"run_id"`
	ID    string `json:"id"`
}

func (q *Queries) LockAccount(ctx context.Context, arg LockAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccount, arg.RunID, arg.ID)
	var i Account
	err := row.Scan(
		&i.RunID,
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Class,
		&i.Customer,
		&i.Balance,
		&i.Held,
		&i.Version,
	)
	return i, err
}

const lockCommand = `-- name: LockCommand :one
SELECT run_id, id, hash, response, created_at FROM command_results WHERE run_id = $1 AND id = $2 FOR UPDATE
`

type LockCommandParams struct {
	RunID string `json:"run_id"`
	ID    string `json:"id"`
}

func (q *Queries) LockCommand(ctx context.Context, arg LockCommandParams) (CommandResult, error) {
	row := q.db.QueryRow(ctx, lockCommand, arg.RunID, arg.ID)
	var i CommandResult
	err := row.Scan(
		&i.RunID,
		&i.ID,
		&i.Hash,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const lockHold = `-- name: LockHold :one
SELECT run_id, id, account_id, amount, state, captured, released FROM holds WHERE run_id = $1 AND id = $2 FOR UPDATE
`

type LockHoldParams struct {
	RunID string `json:"run_id"`
	ID    string `json:"id"`
}

func (q *Queries) LockHold(ctx context.Context, arg LockHoldParams) (Hold, error) {
	row := q.db.QueryRow(ctx, lockHold, arg.RunID, arg.ID)
	var i Hold
	err := row.Scan(
		&i.RunID,
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.State,
		&i.Captured,
		&i.Released,
	)
	return i, err
}

const lockRun = `-- name: LockRun :one
SELECT id, profile, created_at, day, policy, finalized FROM runs WHERE id = $1 FOR SHARE
`

func (q *Queries) LockRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRow(ctx, lockRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.CreatedAt,
		&i.Day,
		&i.Policy,
		&i.Finalized,
	)
	return i, err
}

const nextSequence = `-- name: NextSequence :one
UPDATE journal_clock SET position = position + 1 WHERE run_id = $1 RETURNING position
`

func (q *Queries) NextSequence(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextSequence, runID)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET balance = $3, held = $4, version = version + 1
WHERE run_id = $1 AND id = $2
`

type UpdateAccountParams struct {
	RunID   string `json:"run_id"`
	ID      string `json:"id"`
	Balance int64  `json:"balance"`
	Held    int64  `json:"held"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.RunID,
		arg.ID,
		arg.Balance,
		arg.Held,
	)
	return err
}
