// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	RunID    string `json:"run_id"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Class    string `json:"class"`
	Customer bool   `json:"customer"`
	Balance  int64  `json:"balance"`
	Held     int64  `json:"held"`
	Version  int64  `json:"version"`
}

type AccountCloseJob struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	Day       int32  `json:"day"`
	State     string `json:"state"`
	Reason    string `json:"reason"`
}

type AccountPeriod struct {
	RunID      string `json:"run_id"`
	AccountID  string `json:"account_id"`
	StartDay   int32  `json:"start_day"`
	ThroughDay int32  `json:"through_day"`
	Sequence   int64  `json:"sequence"`
	Amount     int64  `json:"amount"`
}

type CommandResult struct {
	RunID     string             `json:"run_id"`
	ID        string             `json:"id"`
	Hash      string             `json:"hash"`
	Response  []byte             `json:"response"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Control struct {
	RunID            string             `json:"run_id"`
	Eps              int32              `json:"eps"`
	BoostUntil       pgtype.Timestamptz `json:"boost_until"`
	NextAt           pgtype.Timestamptz `json:"next_at"`
	Ordinal          int64              `json:"ordinal"`
	PauseReason      string             `json:"pause_reason"`
	OutboxPauseUntil pgtype.Timestamptz `json:"outbox_pause_until"`
	BudgetSecond     int64              `json:"budget_second"`
	BudgetUsed       int32              `json:"budget_used"`
	GuardUntil       pgtype.Timestamptz `json:"guard_until"`
	GuardReason      string             `json:"guard_reason"`
	GeneratorToken   int64              `json:"generator_token"`
	GeneratorUntil   pgtype.Timestamptz `json:"generator_until"`
}

type DayTransition struct {
	RunID      string             `json:"run_id"`
	FromDay    int32              `json:"from_day"`
	ToDay      int32              `json:"to_day"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
	Instance   string             `json:"instance"`
}

type DeliveryAttemptEvent struct {
	Token      string             `json:"token"`
	Phase      string             `json:"phase"`
	RunID      string             `json:"run_id"`
	Sequence   int64              `json:"sequence"`
	Instance   string             `json:"instance"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

type FeeAssessment struct {
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	ValueDay  int32  `json:"value_day"`
}

type Hold struct {
	RunID     string `json:"run_id"`
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Amount    int64  `json:"amount"`
	State     string `json:"state"`
	Captured  int64  `json:"captured"`
	Released  int64  `json:"released"`
	ValueDay  int32  `json:"value_day"`
}

type HostGuard struct {
	ID         bool               `json:"id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	SafeUntil  pgtype.Timestamptz `json:"safe_until"`
	Reason     string             `json:"reason"`
	Evidence   []byte             `json:"evidence"`
}

type JournalBatch struct {
	RunID     string             `json:"run_id"`
	Sequence  int64              `json:"sequence"`
	CommandID string             `json:"command_id"`
	Kind      string             `json:"kind"`
	BookedDay int32              `json:"booked_day"`
	ValueDay  int32              `json:"value_day"`
	Instance  string             `json:"instance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Envelope  []byte             `json:"envelope"`
}

type JournalClock struct {
	RunID    string `json:"run_id"`
	Position int64  `json:"position"`
}

type NotificationInbox struct {
	RunID      string             `json:"run_id"`
	Sequence   int64              `json:"sequence"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type Outbox struct {
	RunID       string             `json:"run_id"`
	Sequence    int64              `json:"sequence"`
	Attempts    int32              `json:"attempts"`
	ReadyAt     pgtype.Timestamptz `json:"ready_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	LeaseToken  pgtype.Text        `json:"lease_token"`
	LeaseUntil  pgtype.Timestamptz `json:"lease_until"`
}

type Period struct {
	RunID      string `json:"run_id"`
	StartDay   int32  `json:"start_day"`
	ThroughDay int32  `json:"through_day"`
	CommandID  string `json:"command_id"`
}

type PgReplicationSlot struct {
	SlotName           pgtype.Text `json:"slot_name"`
	Database           pgtype.Text `json:"database"`
	RestartLsn         interface{} `json:"restart_lsn"`
	Active             pgtype.Bool `json:"active"`
	WalStatus          pgtype.Text `json:"wal_status"`
	InvalidationReason pgtype.Text `json:"invalidation_reason"`
}

type Posting struct {
	RunID     string `json:"run_id"`
	Sequence  int64  `json:"sequence"`
	Leg       int32  `json:"leg"`
	AccountID string `json:"account_id"`
	Currency  string `json:"currency"`
	Units     int64  `json:"units"`
	ValueDay  int32  `json:"value_day"`
	Kind      string `json:"kind"`
}

type ReplicaHeartbeat struct {
	ID        string             `json:"id"`
	SeenAt    pgtype.Timestamptz `json:"seen_at"`
	Requests  int64              `json:"requests"`
	HeapBytes int64              `json:"heap_bytes"`
}

type Reversal struct {
	RunID       string `json:"run_id"`
	TargetEvent string `json:"target_event"`
	CommandID   string `json:"command_id"`
}

type Run struct {
	ID        string             `json:"id"`
	Profile   string             `json:"profile"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Day       int32              `json:"day"`
	Policy    []byte             `json:"policy"`
	Finalized bool               `json:"finalized"`
}
