// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	RunID    string `json:"run_id"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Class    string `json:"class"`
	Customer bool   `json:"customer"`
	Balance  int64  `json:"balance"`
	Held     int64  `json:"held"`
	Version  int64  `json:"version"`
}

type CommandResult struct {
	RunID     string             `json:"run_id"`
	ID        string             `json:"id"`
	Hash      string             `json:"hash"`
	Response  []byte             `json:"response"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Control struct {
	RunID            string             `json:"run_id"`
	Eps              int32              `json:"eps"`
	BoostUntil       pgtype.Timestamptz `json:"boost_until"`
	NextAt           pgtype.Timestamptz `json:"next_at"`
	Ordinal          int64              `json:"ordinal"`
	PauseReason      string             `json:"pause_reason"`
	OutboxPauseUntil pgtype.Timestamptz `json:"outbox_pause_until"`
	BudgetSecond     int64              `json:"budget_second"`
	BudgetUsed       int32              `json:"budget_used"`
	GuardUntil       pgtype.Timestamptz `json:"guard_until"`
	GuardReason      string             `json:"guard_reason"`
}

type Hold struct {
	RunID     string `json:"run_id"`
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	Amount    int64  `json:"amount"`
	State     string `json:"state"`
	Captured  int64  `json:"captured"`
	Released  int64  `json:"released"`
}

type JournalBatch struct {
	RunID     string             `json:"run_id"`
	Sequence  int64              `json:"sequence"`
	CommandID string             `json:"command_id"`
	Kind      string             `json:"kind"`
	BookedDay int32              `json:"booked_day"`
	ValueDay  int32              `json:"value_day"`
	Instance  string             `json:"instance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Envelope  []byte             `json:"envelope"`
}

type JournalClock struct {
	RunID    string `json:"run_id"`
	Position int64  `json:"position"`
}

type NotificationInbox struct {
	RunID      string             `json:"run_id"`
	Sequence   int64              `json:"sequence"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type Outbox struct {
	RunID       string             `json:"run_id"`
	Sequence    int64              `json:"sequence"`
	Attempts    int32              `json:"attempts"`
	ReadyAt     pgtype.Timestamptz `json:"ready_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

type PgReplicationSlot struct {
	Database   pgtype.Text `json:"database"`
	RestartLsn interface{} `json:"restart_lsn"`
}

type Posting struct {
	RunID     string `json:"run_id"`
	Sequence  int64  `json:"sequence"`
	Leg       int32  `json:"leg"`
	AccountID string `json:"account_id"`
	Currency  string `json:"currency"`
	Units     int64  `json:"units"`
}

type ReplicaHeartbeat struct {
	ID        string             `json:"id"`
	SeenAt    pgtype.Timestamptz `json:"seen_at"`
	Requests  int64              `json:"requests"`
	HeapBytes int64              `json:"heap_bytes"`
}

type Run struct {
	ID        string             `json:"id"`
	Profile   string             `json:"profile"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Day       int32              `json:"day"`
	Policy    []byte             `json:"policy"`
	Finalized bool               `json:"finalized"`
}
