// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_delivery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishDelivery = `-- name: FinishDelivery :execrows
WITH finished AS (
 UPDATE outbox o SET delivered_at=CASE WHEN $2::boolean THEN now() ELSE NULL END,
 ready_at=CASE WHEN $2::boolean THEN ready_at ELSE now()+interval '2 seconds' END,
 lease_token=NULL,lease_until=NULL
 WHERE o.run_id=$4 AND o.sequence=$5 AND o.lease_token=$1
 RETURNING o.run_id,o.sequence
)
INSERT INTO delivery_attempt_events(token,phase,run_id,sequence,instance)
SELECT $1,CASE WHEN $2::boolean THEN 'acknowledged' ELSE 'retry' END,
run_id,sequence,$3 FROM finished
`

type FinishDeliveryParams struct {
	Token    string `json:"token"`
	Success  bool   `json:"success"`
	Instance string `json:"instance"`
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) FinishDelivery(ctx context.Context, arg FinishDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishDelivery,
		arg.Token,
		arg.Success,
		arg.Instance,
		arg.RunID,
		arg.Sequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leaseDelivery = `-- name: LeaseDelivery :one
WITH candidate AS (
 SELECT o.run_id,o.sequence FROM outbox o JOIN controls c ON c.run_id=o.run_id
 WHERE o.run_id=$1 AND o.delivered_at IS NULL AND o.ready_at <= now()
 AND (o.lease_until IS NULL OR o.lease_until < now())
 AND (c.outbox_pause_until IS NULL OR c.outbox_pause_until < now())
 ORDER BY o.ready_at,o.sequence LIMIT 1 FOR UPDATE OF o SKIP LOCKED
), leased AS (
 UPDATE outbox o SET lease_token=$2, lease_until=now()+interval '15 seconds', attempts=attempts+1
 FROM candidate c WHERE o.run_id=c.run_id AND o.sequence=c.sequence RETURNING o.run_id,o.sequence
), audit AS (
 INSERT INTO delivery_attempt_events(token,phase,run_id,sequence,instance)
 SELECT $2,'claimed',run_id,sequence,$3 FROM leased
)
SELECT b.run_id,b.sequence,b.envelope FROM journal_batches b JOIN leased l USING(run_id,sequence)
`

type LeaseDeliveryParams struct {
	RunID    string      `json:"run_id"`
	Token    pgtype.Text `json:"token"`
	Instance string      `json:"instance"`
}

type LeaseDeliveryRow struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
	Envelope []byte `json:"envelope"`
}

func (q *Queries) LeaseDelivery(ctx context.Context, arg LeaseDeliveryParams) (LeaseDeliveryRow, error) {
	row := q.db.QueryRow(ctx, leaseDelivery, arg.RunID, arg.Token, arg.Instance)
	var i LeaseDeliveryRow
	err := row.Scan(&i.RunID, &i.Sequence, &i.Envelope)
	return i, err
}

const receiveNotification = `-- name: ReceiveNotification :one
WITH matched AS (
 SELECT b.run_id,b.sequence FROM journal_batches b WHERE b.run_id=$1 AND b.sequence=$2 AND b.envelope=$3::jsonb
), accepted AS (
 INSERT INTO notification_inbox(run_id,sequence) SELECT run_id,sequence FROM matched ON CONFLICT DO NOTHING
)
SELECT EXISTS(SELECT FROM matched)::boolean
`

type ReceiveNotificationParams struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
	Envelope []byte `json:"envelope"`
}

func (q *Queries) ReceiveNotification(ctx context.Context, arg ReceiveNotificationParams) (bool, error) {
	row := q.db.QueryRow(ctx, receiveNotification, arg.RunID, arg.Sequence, arg.Envelope)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
