// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement.sql

package db

import (
	"context"
)

const openingSettlementLines = `-- name: OpeningSettlementLines :many
SELECT b.command_id AS reference,p.currency,p.value_day,sum(p.units)::text AS amount
FROM postings p JOIN journal_batches b USING(run_id,sequence)
WHERE p.run_id=$1 AND p.sequence<=$2::bigint
 AND p.account_id IN ('settlement-AED','settlement-BHD')
 AND b.command_id LIKE 'seed-%'
GROUP BY b.sequence,b.command_id,p.currency,p.value_day
ORDER BY b.sequence,p.currency,p.value_day LIMIT 10001
`

type OpeningSettlementLinesParams struct {
	RunID  string `json:"run_id"`
	Cutoff int64  `json:"cutoff"`
}

type OpeningSettlementLinesRow struct {
	Reference string `json:"reference"`
	Currency  string `json:"currency"`
	ValueDay  int32  `json:"value_day"`
	Amount    string `json:"amount"`
}

func (q *Queries) OpeningSettlementLines(ctx context.Context, arg OpeningSettlementLinesParams) ([]OpeningSettlementLinesRow, error) {
	rows, err := q.db.Query(ctx, openingSettlementLines, arg.RunID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpeningSettlementLinesRow{}
	for rows.Next() {
		var i OpeningSettlementLinesRow
		if err := rows.Scan(
			&i.Reference,
			&i.Currency,
			&i.ValueDay,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
