// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const statementAccount = `-- name: StatementAccount :one
SELECT id, name, currency, class, customer FROM accounts WHERE run_id=$1 AND id=$2
`

type StatementAccountParams struct {
	RunID string `json:"run_id"`
	ID    string `json:"id"`
}

type StatementAccountRow struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
	Class    string `json:"class"`
	Customer bool   `json:"customer"`
}

func (q *Queries) StatementAccount(ctx context.Context, arg StatementAccountParams) (StatementAccountRow, error) {
	row := q.db.QueryRow(ctx, statementAccount, arg.RunID, arg.ID)
	var i StatementAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Class,
		&i.Customer,
	)
	return i, err
}

const statementLines = `-- name: StatementLines :many
SELECT p.sequence,p.leg,p.units,p.value_day,p.kind,b.booked_day,b.created_at,b.command_id,b.instance
FROM postings p JOIN journal_batches b USING (run_id,sequence)
WHERE p.run_id=$1 AND p.account_id=$2
 AND p.sequence<=$3::bigint
 AND (p.sequence,p.leg) > ($4::bigint,$5::integer)
ORDER BY p.sequence,p.leg LIMIT $6::integer
`

type StatementLinesParams struct {
	RunID         string `json:"run_id"`
	AccountID     string `json:"account_id"`
	Cutoff        int64  `json:"cutoff"`
	AfterSequence int64  `json:"after_sequence"`
	AfterLeg      int32  `json:"after_leg"`
	PageLimit     int32  `json:"page_limit"`
}

type StatementLinesRow struct {
	Sequence  int64              `json:"sequence"`
	Leg       int32              `json:"leg"`
	Units     int64              `json:"units"`
	ValueDay  int32              `json:"value_day"`
	Kind      string             `json:"kind"`
	BookedDay int32              `json:"booked_day"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CommandID string             `json:"command_id"`
	Instance  string             `json:"instance"`
}

func (q *Queries) StatementLines(ctx context.Context, arg StatementLinesParams) ([]StatementLinesRow, error) {
	rows, err := q.db.Query(ctx, statementLines,
		arg.RunID,
		arg.AccountID,
		arg.Cutoff,
		arg.AfterSequence,
		arg.AfterLeg,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatementLinesRow{}
	for rows.Next() {
		var i StatementLinesRow
		if err := rows.Scan(
			&i.Sequence,
			&i.Leg,
			&i.Units,
			&i.ValueDay,
			&i.Kind,
			&i.BookedDay,
			&i.CreatedAt,
			&i.CommandID,
			&i.Instance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementTotals = `-- name: StatementTotals :one
SELECT count(*) AS posting_count,
 COALESCE(sum(units),0)::text AS closing_units,
 COALESCE(sum(units) FILTER (WHERE (sequence,leg) <= ($1::bigint,$2::integer)),0)::text AS opening_units,
 COALESCE(sum(units) FILTER (WHERE units>0),0)::text AS debit_units,
 COALESCE(-sum(units) FILTER (WHERE units<0),0)::text AS credit_units
FROM postings
WHERE run_id=$3 AND account_id=$4 AND sequence<=$5::bigint
`

type StatementTotalsParams struct {
	AfterSequence int64  `json:"after_sequence"`
	AfterLeg      int32  `json:"after_leg"`
	RunID         string `json:"run_id"`
	AccountID     string `json:"account_id"`
	Cutoff        int64  `json:"cutoff"`
}

type StatementTotalsRow struct {
	PostingCount int64  `json:"posting_count"`
	ClosingUnits string `json:"closing_units"`
	OpeningUnits string `json:"opening_units"`
	DebitUnits   string `json:"debit_units"`
	CreditUnits  string `json:"credit_units"`
}

func (q *Queries) StatementTotals(ctx context.Context, arg StatementTotalsParams) (StatementTotalsRow, error) {
	row := q.db.QueryRow(ctx, statementTotals,
		arg.AfterSequence,
		arg.AfterLeg,
		arg.RunID,
		arg.AccountID,
		arg.Cutoff,
	)
	var i StatementTotalsRow
	err := row.Scan(
		&i.PostingCount,
		&i.ClosingUnits,
		&i.OpeningUnits,
		&i.DebitUnits,
		&i.CreditUnits,
	)
	return i, err
}
