// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package db

import (
	"context"
)

const acknowledgeGeneratedCommand = `-- name: AcknowledgeGeneratedCommand :execrows
UPDATE controls SET ordinal = ordinal + 1,
  generator_until = NULL,
  eps = CASE WHEN boost_until < clock_timestamp() THEN 1 ELSE eps END,
  next_at = clock_timestamp() + make_interval(secs => 1.0 / GREATEST(1, CASE WHEN boost_until < clock_timestamp() THEN 1 ELSE eps END))
WHERE run_id = $1 AND ordinal = $2 AND generator_token = $3
`

type AcknowledgeGeneratedCommandParams struct {
	RunID          string `json:"run_id"`
	Ordinal        int64  `json:"ordinal"`
	GeneratorToken int64  `json:"generator_token"`
}

func (q *Queries) AcknowledgeGeneratedCommand(ctx context.Context, arg AcknowledgeGeneratedCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeGeneratedCommand, arg.RunID, arg.Ordinal, arg.GeneratorToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const admit = `-- name: Admit :execrows
UPDATE controls SET
  budget_used = CASE WHEN budget_second = floor(extract(epoch FROM clock_timestamp()))::bigint
    THEN budget_used + 1 ELSE 1 END,
  budget_second = floor(extract(epoch FROM clock_timestamp()))::bigint
WHERE run_id = 'demo' AND pause_reason = '' AND guard_until > now()
  AND EXISTS (SELECT FROM host_guard WHERE id AND safe_until > now())
  AND (budget_second <> floor(extract(epoch FROM clock_timestamp()))::bigint OR budget_used < 20)
  AND (SELECT position FROM journal_clock WHERE run_id = 'demo') < 100000
`

func (q *Queries) Admit(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, admit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimGeneratedCommand = `-- name: ClaimGeneratedCommand :one
UPDATE controls SET generator_token = generator_token + 1,
  generator_until = clock_timestamp() + interval '5 seconds'
WHERE run_id = $1 AND eps > 0 AND next_at <= clock_timestamp()
  AND pause_reason = '' AND guard_until > clock_timestamp()
  AND (generator_until IS NULL OR generator_until <= clock_timestamp())
RETURNING ordinal, generator_token
`

type ClaimGeneratedCommandRow struct {
	Ordinal        int64 `json:"ordinal"`
	GeneratorToken int64 `json:"generator_token"`
}

func (q *Queries) ClaimGeneratedCommand(ctx context.Context, runID string) (ClaimGeneratedCommandRow, error) {
	row := q.db.QueryRow(ctx, claimGeneratedCommand, runID)
	var i ClaimGeneratedCommandRow
	err := row.Scan(&i.Ordinal, &i.GeneratorToken)
	return i, err
}

const databaseFootprint = `-- name: DatabaseFootprint :one
SELECT pg_database_size(current_database())::bigint AS size,
  COALESCE((SELECT max(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn))
    FROM pg_replication_slots WHERE database = current_database()), 0)::bigint AS retained
`

type DatabaseFootprintRow struct {
	Size     int64 `json:"size"`
	Retained int64 `json:"retained"`
}

func (q *Queries) DatabaseFootprint(ctx context.Context) (DatabaseFootprintRow, error) {
	row := q.db.QueryRow(ctx, databaseFootprint)
	var i DatabaseFootprintRow
	err := row.Scan(&i.Size, &i.Retained)
	return i, err
}

const heartbeat = `-- name: Heartbeat :exec
INSERT INTO replica_heartbeats (id, seen_at, heap_bytes) VALUES ($1, now(), $2)
ON CONFLICT (id) DO UPDATE SET seen_at = now(), heap_bytes = excluded.heap_bytes
`

type HeartbeatParams struct {
	ID        string `json:"id"`
	HeapBytes int64  `json:"heap_bytes"`
}

func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) error {
	_, err := q.db.Exec(ctx, heartbeat, arg.ID, arg.HeapBytes)
	return err
}

const listReplicas = `-- name: ListReplicas :many
SELECT id, seen_at, requests, heap_bytes FROM replica_heartbeats ORDER BY id LIMIT 10
`

func (q *Queries) ListReplicas(ctx context.Context) ([]ReplicaHeartbeat, error) {
	rows, err := q.db.Query(ctx, listReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplicaHeartbeat{}
	for rows.Next() {
		var i ReplicaHeartbeat
		if err := rows.Scan(
			&i.ID,
			&i.SeenAt,
			&i.Requests,
			&i.HeapBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGeneratedCommand = `-- name: LockGeneratedCommand :one
SELECT ordinal FROM controls
WHERE run_id = $1 AND ordinal = $2 AND generator_token = $3
  AND generator_until > clock_timestamp() AND eps > 0
  AND pause_reason = '' AND guard_until > clock_timestamp()
FOR UPDATE
`

type LockGeneratedCommandParams struct {
	RunID          string `json:"run_id"`
	Ordinal        int64  `json:"ordinal"`
	GeneratorToken int64  `json:"generator_token"`
}

func (q *Queries) LockGeneratedCommand(ctx context.Context, arg LockGeneratedCommandParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockGeneratedCommand, arg.RunID, arg.Ordinal, arg.GeneratorToken)
	var ordinal int64
	err := row.Scan(&ordinal)
	return ordinal, err
}

const pauseOutbox = `-- name: PauseOutbox :execrows
UPDATE controls SET outbox_pause_until = now() + interval '15 seconds'
WHERE run_id = 'demo' AND (outbox_pause_until IS NULL OR outbox_pause_until < now() - interval '45 seconds')
 AND EXISTS (SELECT FROM host_guard WHERE id AND safe_until > now())
`

func (q *Queries) PauseOutbox(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pauseOutbox)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshGuard = `-- name: RefreshGuard :exec
UPDATE controls SET guard_until = CASE WHEN $1::text = ''
  THEN now() + interval '10 seconds' ELSE now() END,
  guard_reason = $1 WHERE run_id = 'demo'
`

func (q *Queries) RefreshGuard(ctx context.Context, reason string) error {
	_, err := q.db.Exec(ctx, refreshGuard, reason)
	return err
}

const setRate = `-- name: SetRate :execrows
UPDATE controls SET eps = $1, boost_until = CASE WHEN $1 > 1
  THEN now() + interval '60 seconds' ELSE NULL END WHERE run_id = 'demo'
  AND ($1 = 0 OR EXISTS (SELECT FROM host_guard WHERE id AND safe_until > now()))
`

func (q *Queries) SetRate(ctx context.Context, eps int32) (int64, error) {
	result, err := q.db.Exec(ctx, setRate, eps)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const simulationStatus = `-- name: SimulationStatus :one
SELECT c.eps, c.ordinal, j.position, c.guard_reason, c.pause_reason,
  COALESCE(c.guard_until > now(), false)::boolean AS fresh,
  (SELECT count(*) FROM outbox WHERE run_id='demo' AND delivered_at IS NULL) AS pending,
  pg_database_size(current_database())::bigint AS database_bytes
FROM controls c JOIN journal_clock j USING (run_id) WHERE c.run_id = 'demo'
`

type SimulationStatusRow struct {
	Eps           int32  `json:"eps"`
	Ordinal       int64  `json:"ordinal"`
	Position      int64  `json:"position"`
	GuardReason   string `json:"guard_reason"`
	PauseReason   string `json:"pause_reason"`
	Fresh         bool   `json:"fresh"`
	Pending       int64  `json:"pending"`
	DatabaseBytes int64  `json:"database_bytes"`
}

func (q *Queries) SimulationStatus(ctx context.Context) (SimulationStatusRow, error) {
	row := q.db.QueryRow(ctx, simulationStatus)
	var i SimulationStatusRow
	err := row.Scan(
		&i.Eps,
		&i.Ordinal,
		&i.Position,
		&i.GuardReason,
		&i.PauseReason,
		&i.Fresh,
		&i.Pending,
		&i.DatabaseBytes,
	)
	return i, err
}
