// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package db

import (
	"context"
)

const acceptDelivery = `-- name: AcceptDelivery :exec
INSERT INTO notification_inbox (run_id, sequence) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AcceptDeliveryParams struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) AcceptDelivery(ctx context.Context, arg AcceptDeliveryParams) error {
	_, err := q.db.Exec(ctx, acceptDelivery, arg.RunID, arg.Sequence)
	return err
}

const acknowledgeGeneratedCommand = `-- name: AcknowledgeGeneratedCommand :exec
UPDATE controls SET ordinal = ordinal + 1,
  eps = CASE WHEN boost_until < now() THEN 1 ELSE eps END,
  next_at = now() + make_interval(secs => 1.0 / GREATEST(1, CASE WHEN boost_until < now() THEN 1 ELSE eps END))
WHERE run_id = 'demo' AND ordinal = $1
`

func (q *Queries) AcknowledgeGeneratedCommand(ctx context.Context, ordinal int64) error {
	_, err := q.db.Exec(ctx, acknowledgeGeneratedCommand, ordinal)
	return err
}

const admit = `-- name: Admit :execrows
UPDATE controls SET
  budget_used = CASE WHEN budget_second = floor(extract(epoch FROM clock_timestamp()))::bigint
    THEN budget_used + 1 ELSE 1 END,
  budget_second = floor(extract(epoch FROM clock_timestamp()))::bigint
WHERE run_id = 'demo' AND pause_reason = '' AND guard_until > now()
  AND (budget_second <> floor(extract(epoch FROM clock_timestamp()))::bigint OR budget_used < 20)
  AND (SELECT position FROM journal_clock WHERE run_id = 'demo') < 100000
`

func (q *Queries) Admit(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, admit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDelivery = `-- name: ClaimDelivery :one
SELECT o.run_id, o.sequence FROM outbox o JOIN controls c ON c.run_id = o.run_id
WHERE delivered_at IS NULL AND ready_at <= now()
  AND (c.outbox_pause_until IS NULL OR c.outbox_pause_until < now())
ORDER BY o.sequence LIMIT 1 FOR UPDATE OF o SKIP LOCKED
`

type ClaimDeliveryRow struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) ClaimDelivery(ctx context.Context) (ClaimDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimDelivery)
	var i ClaimDeliveryRow
	err := row.Scan(&i.RunID, &i.Sequence)
	return i, err
}

const completeDelivery = `-- name: CompleteDelivery :exec
UPDATE outbox SET delivered_at = now(), attempts = attempts + 1 WHERE run_id = $1 AND sequence = $2
`

type CompleteDeliveryParams struct {
	RunID    string `json:"run_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) CompleteDelivery(ctx context.Context, arg CompleteDeliveryParams) error {
	_, err := q.db.Exec(ctx, completeDelivery, arg.RunID, arg.Sequence)
	return err
}

const databaseFootprint = `-- name: DatabaseFootprint :one
SELECT pg_database_size(current_database())::bigint AS size,
  COALESCE((SELECT max(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn))
    FROM pg_replication_slots WHERE database = current_database()), 0)::bigint AS retained
`

type DatabaseFootprintRow struct {
	Size     int64 `json:"size"`
	Retained int64 `json:"retained"`
}

func (q *Queries) DatabaseFootprint(ctx context.Context) (DatabaseFootprintRow, error) {
	row := q.db.QueryRow(ctx, databaseFootprint)
	var i DatabaseFootprintRow
	err := row.Scan(&i.Size, &i.Retained)
	return i, err
}

const heartbeat = `-- name: Heartbeat :exec
INSERT INTO replica_heartbeats (id, seen_at, heap_bytes) VALUES ($1, now(), $2)
ON CONFLICT (id) DO UPDATE SET seen_at = now(), heap_bytes = excluded.heap_bytes
`

type HeartbeatParams struct {
	ID        string `json:"id"`
	HeapBytes int64  `json:"heap_bytes"`
}

func (q *Queries) Heartbeat(ctx context.Context, arg HeartbeatParams) error {
	_, err := q.db.Exec(ctx, heartbeat, arg.ID, arg.HeapBytes)
	return err
}

const listReplicas = `-- name: ListReplicas :many
SELECT id, seen_at, requests, heap_bytes FROM replica_heartbeats ORDER BY id LIMIT 10
`

func (q *Queries) ListReplicas(ctx context.Context) ([]ReplicaHeartbeat, error) {
	rows, err := q.db.Query(ctx, listReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplicaHeartbeat{}
	for rows.Next() {
		var i ReplicaHeartbeat
		if err := rows.Scan(
			&i.ID,
			&i.SeenAt,
			&i.Requests,
			&i.HeapBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGeneratedCommand = `-- name: NextGeneratedCommand :one
SELECT ordinal FROM controls WHERE run_id = 'demo' AND eps > 0 AND next_at <= now()
  AND pause_reason = '' AND guard_until > now()
`

func (q *Queries) NextGeneratedCommand(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextGeneratedCommand)
	var ordinal int64
	err := row.Scan(&ordinal)
	return ordinal, err
}

const pauseOutbox = `-- name: PauseOutbox :execrows
UPDATE controls SET outbox_pause_until = now() + interval '15 seconds'
WHERE run_id = 'demo' AND (outbox_pause_until IS NULL OR outbox_pause_until < now() - interval '45 seconds')
`

func (q *Queries) PauseOutbox(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pauseOutbox)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshGuard = `-- name: RefreshGuard :exec
UPDATE controls SET guard_until = CASE WHEN $1::text = ''
  THEN now() + interval '10 seconds' ELSE now() END,
  guard_reason = $1 WHERE run_id = 'demo'
`

func (q *Queries) RefreshGuard(ctx context.Context, reason string) error {
	_, err := q.db.Exec(ctx, refreshGuard, reason)
	return err
}

const setRate = `-- name: SetRate :exec
UPDATE controls SET eps = $1, boost_until = CASE WHEN $1 > 1
  THEN now() + interval '60 seconds' ELSE NULL END WHERE run_id = 'demo'
`

func (q *Queries) SetRate(ctx context.Context, eps int32) error {
	_, err := q.db.Exec(ctx, setRate, eps)
	return err
}

const simulationStatus = `-- name: SimulationStatus :one
SELECT c.eps, c.ordinal, j.position, c.guard_reason, c.pause_reason,
  COALESCE(c.guard_until > now(), false)::boolean AS fresh,
  (SELECT count(*) FROM outbox WHERE delivered_at IS NULL) AS pending,
  pg_database_size(current_database())::bigint AS database_bytes
FROM controls c JOIN journal_clock j USING (run_id) WHERE c.run_id = 'demo'
`

type SimulationStatusRow struct {
	Eps           int32  `json:"eps"`
	Ordinal       int64  `json:"ordinal"`
	Position      int64  `json:"position"`
	GuardReason   string `json:"guard_reason"`
	PauseReason   string `json:"pause_reason"`
	Fresh         bool   `json:"fresh"`
	Pending       int64  `json:"pending"`
	DatabaseBytes int64  `json:"database_bytes"`
}

func (q *Queries) SimulationStatus(ctx context.Context) (SimulationStatusRow, error) {
	row := q.db.QueryRow(ctx, simulationStatus)
	var i SimulationStatusRow
	err := row.Scan(
		&i.Eps,
		&i.Ordinal,
		&i.Position,
		&i.GuardReason,
		&i.PauseReason,
		&i.Fresh,
		&i.Pending,
		&i.DatabaseBytes,
	)
	return i, err
}
